=== synergynet/synergynet2.1/SynergySpace2.1/src_synergynet/data/contentitems/schemas/contentitems_gesture_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://tel.dur.ac.uk/xml/schemas/contentitems_gesture_schema" xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_gesture_schema" elementFormDefault="qualified">

    <complexType name="ContentItemsType">
    	<sequence>
    		<element name="items" type="tns:ItemListType" minOccurs="1"
    			maxOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="description" type="string" use="required"></attribute>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="author" type="string" use="required"></attribute>
    	<attribute name="license" type="string" use="required"></attribute> 	   	
    	 	
    </complexType>

    <element name="contentitems" type="tns:ContentItemsType"></element>

    <complexType name="ItemType">
    	<sequence>
    		<element name="attributes" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    	 	
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="manipulate" type="string"></attribute>
    	<attribute name="isBoundaryEnabled" type="string"></attribute>
    	<attribute name="rotateTranslateScalable" type="string"></attribute>
    	<attribute name="bringToTopable" type="string"></attribute>
    	<attribute name="snapable" type="string"></attribute>
    	
    </complexType>

    <complexType name="ItemListType">
    	<sequence>
    		<element name="item" type="tns:ItemType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

	 <attribute name="NewAttribute" type="string"></attribute>
</schema>

=== synergynet/synergynet2.1/SynergySpace2.1/bin/data/diamondranking/ict/ict_gesture.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:contentitems author="Steve Higgins"
	description="Dinner disaster: can you work out what Mike should have to eat? - guesture attribute"
	license="restricted" 
	name ="Dinner disaster: can you work out what Mike should have to eat? - guesture attribute"

	xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_gesture_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tel.dur.ac.uk/xml/schemas/contentitems_gesture_schema ../../data/contentitems/schemas/contentitems_gesture_schema.xsd ">
	<tns:items>
		
		<tns:item 	
			id="ICT1"
			snapable ="true"
		>
		</tns:item>	
		<tns:item 	
			id="ICT2"
			snapable ="true"
		>	
		</tns:item>	
		<tns:item 	
			id="ICT3"
			snapable ="true"
		>		
		</tns:item>
		<tns:item 	
			id="ICT4"
			snapable ="true"
		>		
		</tns:item>
		<tns:item 	
			id="ICT5"
			snapable ="true"
		>		
		</tns:item>
		<tns:item 	
			id="ICT6"
			snapable ="true"
		>		
		</tns:item>
		<tns:item 	
			id="ICT7"
			snapable ="true"
		>		
		</tns:item>
		<tns:item 	
			id="ICT8"
			snapable ="true"
		>		
		</tns:item>
		<tns:item 	
			id="ICT9"
			snapable ="true"
		>		
		</tns:item>
		
		
		<tns:item 	
			id="ICT10"
			rotateTranslateScalable = "false"
			bringToTopable = "false"
		>	
		</tns:item>	
		<tns:item 	
			id="ICT11"
			rotateTranslateScalable = "false"
			bringToTopable = "false"
		>		
		</tns:item>
		<tns:item 	
			id="ICT12"
			rotateTranslateScalable = "false"
			bringToTopable = "false"
		>		
		</tns:item>
		<tns:item 	
			id="ICT13"
			rotateTranslateScalable = "false"
			bringToTopable = "false"
		>		
		</tns:item>
		<tns:item 	
			id="ICT14"
			rotateTranslateScalable = "false"
			bringToTopable = "false"
		>		
		</tns:item>
		<tns:item 	
			id="ICT15"
			rotateTranslateScalable = "false"
			bringToTopable = "false"
		>		
		</tns:item>
		<tns:item 	
			id="ICT16"
			rotateTranslateScalable = "false"
			bringToTopable = "false"
		>		
		</tns:item>
		<tns:item 	
			id="ICT17"
			rotateTranslateScalable = "false"
			bringToTopable = "false"
		>		
		</tns:item>
		<tns:item 	
			id="ICT18"
			rotateTranslateScalable = "false"
			bringToTopable = "false"
		>		
		</tns:item>
		
		<tns:item 	
			id="ICT19"
			rotateTranslateScalable = "false"
			bringToTopable = "false"
		>		
		</tns:item>
	</tns:items>
</tns:contentitems>
