=== synergynet/synergynet2.1/SynergySpace2.1/src_synergynet/data/contentitems/schemas/contentitems_location_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://tel.dur.ac.uk/xml/schemas/contentitems_location_schema" xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_location_schema" elementFormDefault="qualified">

    <complexType name="ContentItemType">
    	<sequence>
    		<element name="items" type="tns:ItemListType" minOccurs="1"
    			maxOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="description" type="string" use="required"></attribute>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="author" type="string" use="required"></attribute>
    	<attribute name="license" type="string" use="required"></attribute>
    	
    	<attribute name="defaultLocationX" type="string"></attribute>
    	<attribute name="defaultLocationY" type="string"></attribute>
    	<attribute name="defaultLocationZ" type="string"></attribute>
    	<attribute name="defaultSortOrder" type="string"></attribute>
    	
    </complexType>

    <element name="contentitems" type="tns:ContentItemType"></element>

    <complexType name="ItemType">
    	<sequence>
    		<element name="attributes" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="x" type="string"></attribute>
    	<attribute name="y" type="string"></attribute>
    	<attribute name="z" type="string"></attribute>
    	<attribute name="sortOrder" type="string"></attribute>
    	
    </complexType>


    <complexType name="ItemListType">
    	<sequence>
    		<element name="item" type="tns:ItemType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

	 <attribute name="NewAttribute" type="string"></attribute>
</schema>

=== synergynet/synergynet2.1/SynergySpace2.1/bin/data/diamondranking/imagetest/imagetest_location.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:contentitems author="Steve Higgins"
	description="ICT for Learning"
	license="restricted" 
	name ="ICT for Learning"
	
	defaultLocationX ="150"
	defaultLocationY = "150"
	defaultLocationZ = "0"
	
	xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_location_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tel.dur.ac.uk/xml/schemas/contentitems_location_schema ../../data/contentitems/schemas/contentitems_location_schema.xsd ">
	<tns:items>
		<tns:item 
			id="IT10"
			x="312"
			y="384"
			z="0">
		</tns:item>
		<tns:item 
			id="IT11"
			x="712"
			y="384"
			z="0">
		</tns:item>
		<tns:item 
			id="IT12"
			x="412"
			y="264"
			z="0">		
		</tns:item>
		<tns:item 
			id="IT13"
			x="612"
			y="264"
			z="0">		
		</tns:item>
		<tns:item
			id="IT14"
			x="512"
			y="144"
			z="0">		
		</tns:item>
		<tns:item 
			id="IT15"
			x="612"
			y="504"
			z="0">		
		</tns:item>
		<tns:item
			id="IT16"
			x="412"
			y="504"
			z="0">		
		</tns:item>
		<tns:item 
			id="IT17"
			x="512"
			y="384"
			z="0">				
		</tns:item>
		<tns:item
			id="IT18"
			x="512"
			y="624"
			z="0">		
		</tns:item>
		<tns:item 	
			id="IT19"
			x = "517"
			y = "720"
			z ="0"
			sortOrder="99999"
		>
		</tns:item>
	</tns:items>
</tns:contentitems>
