=== synergynet/synergynet2.1/SynergySpace2.1/bin/data/contentitems/schemas/contentitems_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://tel.dur.ac.uk/xml/schemas/contentitems_schema" xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_schema" elementFormDefault="qualified">

    <complexType name="ContentItemsType">
    	<sequence>
    		<element name="items" type="tns:ItemListType" minOccurs="1"
    			maxOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="description" type="string" use="required"></attribute>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="author" type="string" use="required"></attribute>
    	<attribute name="license" type="string" use="required"></attribute>
    	<attribute name="question" type="string"></attribute>
    	
    	<attribute name="locationFile" type="string"></attribute>
    	<attribute name="appearanceFile" type="string"></attribute>
    	<attribute name="defaultAppearanceFile" type="string"></attribute>
    	<attribute name="gestureFile" type="string"></attribute>

    </complexType>

    <element name="contentitems" type="tns:ContentItemsType"></element>

    <complexType name="ItemType">
    	<sequence>
    		<element name="attributes" type="string"></element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="content-type" type="string"></attribute>  	
    	<attribute name="contentItemType" type="string" use="required"></attribute>  
    	<attribute name="category" type="string" use="required"></attribute> 	
    	<attribute name="imagePath" type="string"></attribute> 
    	<attribute name="content" type="string"></attribute> 
    	
    </complexType>


    <complexType name="ItemListType">
    	<sequence>
    		<element name="item" type="tns:ItemType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <attribute name="NewAttribute" type="string"></attribute>

</schema>

=== synergynet/synergynet2.1/SynergySpace2.1/src_synergynet/data/mysteries/robert_dixon/robert_dixon.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:contentitems
	xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tel.dur.ac.uk/xml/schemas/mystery_schema ../../data/contentitems/schemas/contentitems_schema.xsd "
	author="Steve Higgins"
	description="What happened to Robert Dixon? Whose fault was it?"
	license="restricted" name="What happened to Robert Dixon? Whose fault was it?"
	
	locationFile="data/mysteries/robert_dixon/robert_dixon_location.xml"
	appearanceFile="data/mysteries/robert_dixon/robert_dixon_apparence.xml"
	gestureFile="data/mysteries/robert_dixon/robert_dixon_gesture.xml"
	defaultAppearanceFile="data/mysteries/defaultApparence.xml"
	
	>
	<tns:items>
		<tns:item content-type="text/plain"
			id="RD1"
			content = "Mrs. Richardson, the mine owner’s wife, wants an expensive house in the country because she says that it is too dirty living near the mine."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD2"
			content ="The coalmine is the only employment in the village." 
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD3"
			content ="The mine supervisor, John Robson, was feeling ill that morning as a result of too much ale the night before and did not check the wheels on the carts like he sometimes did."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD4"
			content = "The mine inspectors had reported that there was not enough fresh air in the mine, but John Robson thought they were being too fussy and had not done anything about it."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD5"
			content ="At this time it was not against the law for 10 year-old boys to work underground." 
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD6"
			content ="Workers in the mine had to supply their own candles."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD7"
			content ="Wages varied depending on the price of coal. If the price was low the miners had to dig more coal to keep the same wage and worked longer hours."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD8"
			content ="Robert Dixon is 10 years old. He works underground as a trapper. He opens the doors to let the coal trucks through. He has been working at the mine for two years."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD9"
			content ="Last year Robert’s dad, William Dixon, died in an explosion at the pit. 53 men and boys were killed. A fund was set up for their families. Sir Charles Richardson, the mine owner, gave some money, but there was not much for each family."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD10"
			content ="Robert usually works from 6 am to 6 pm, but has recently had to work longer because his wages had gone down."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD11"
			content ="The weather has been unusually hot this summer."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD12"
			content ="Robert gets up at 5 am. He has bread and tea for breakfast and then walks to the pit. He has a break at 11 am for bread and tea. When he gets home he has some more bread and cheese or meat, if the family can afford it, then goes to bed."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>

		<tns:item content-type="text/plain"
			id="RD13"
			content ="Because of the war there has been less trade overseas and there is less demand for coal from the factories, so the price of coal is very low."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD14"
			content ="Ropes operated by a steam engine pull the coal trucks down the mine. Only one person is needed to pull a whole line of trucks. Until recently horses pulled the trucks."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RD15"
			content ="Robert’s mother, Anna Dixon, has been very ill after the birth of her ninth child. She has to stay in bed."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
				<tns:item content-type="text/plain"
			id="RD16"
			content ="Robert has six younger brothers and sisters. His older sister, Mary, works as a scullery maid for Sir Charles. His older brother William is a miner at the same pit as Robert."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="RDTitle"
			content ="What happened to Robert Dixon? Whose fault was it?"
			contentItemType ="MultiLineTextLabel"
			category = "title"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
	</tns:items>
</tns:contentitems>

=== synergynet/synergynet2.1/SynergySpace2.1/src_synergynet/data/mysteries/waltzer/waltzer.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:contentitems
	xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tel.dur.ac.uk/xml/schemas/mystery_schema ../../data/contentitems/schemas/contentitems_schema.xsd "
	author="Steve Higgins"
	description="How much will it cost the Waltzer owner for enough cuddly monkeys for a day?"
	license="restricted" name="How much will it cost the Waltzer owner for enough cuddly monkeys for a day?"
	
	locationFile="data/mysteries/waltzer/waltzer_location.xml"
	appearanceFile="data/mysteries/waltzer/waltzer_apparence.xml"
	gestureFile="data/mysteries/waltzer/waltzer_gesture.xml"
	defaultAppearanceFile="data/mysteries/defaultApparence.xml"
	
	>
	<tns:items>
		<tns:item content-type="text/plain"
			id="Waltzer1"
			content = "At the fair there is a Waltzer."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="Waltzer2"
			content ="To get people to go on the Waltzer the owner offers a free prize." 
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="Waltzer3"
			content ="The owner decides that every 10th person will be given a cuddly toy monkey."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="Waltzer4"
			content = "The monkeys look very happy."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="Waltzer5"
			content ="It costs the owner Â£2 for one monkey. " 
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="Waltzer6"
			content ="5 people can sit together in a car on the Waltzer."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="Waltzer7"
			content ="There are 10 cars altogether on the Waltzer."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="Waltzer8"
			content ="You must be at least 9 years old to ride the Waltzer."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="Waltzer9"
			content ="There are 10 rides every hour."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="Waltzer10"
			content ="The fair is open for 8 hours a day."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="Waltzer11"
			content ="On average half of the spaces are taken for each during the all day."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="Waltzer12"
			content ="The music on the Waltzer is played very loud all day."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		
		<tns:item content-type="text/plain"
			id="WaltzerTitle"
			content ="How much will it cost the Waltzer owner for enough cuddly monkeys for a day?"
			contentItemType ="MultiLineTextLabel"
			category = "title"
			>
			<tns:attributes></tns:attributes>
		</tns:item>

	</tns:items>
</tns:contentitems>

=== synergynet/synergynet2.1/SynergySpace2.1/src_synergynet/data/mysteries/schooltrip/schooltrip.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:contentitems
	xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tel.dur.ac.uk/xml/schemas/mystery_schema ../../data/contentitems/schemas/contentitems_schema.xsd "
	author="Steve Higgins"
	description="Does Nathan miss the bus for the school trip?"
	license="restricted" name="Does Nathan miss the bus for the school trip?"

	locationFile="data/mysteries/schooltrip/schooltrip_location.xml"
	appearanceFile="data/mysteries/schooltrip/schooltrip_apparence.xml"
	gestureFile="data/mysteries/schooltrip/schooltrip_gesture.xml"
	defaultAppearanceFile="data/mysteries/defaultApparence.xml"
	
	>
	<tns:items>
		<tns:item content-type="text/plain"
			id="SchoolTrip1"
			content = "Nathan’s mother is ready to leave by car for work at 8.10 am. She usually gives Nathan a lift and it takes about quarter of an hour to get to his school. "
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTrip2"
			content ="Today, the day of the school trip, the car won’t start." 
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTrip3"
			content ="The breakdown company say they can get someone to the house in30 minutes. An average repair takes another half an hour."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTrip4"
			content = "Nathan sets off walking at 8.20 am."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTrip5"
			content ="It takes 15 minutes to walk to the park." 
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTrip6"
			content ="When Nathan gets to the park he realizes he has left his packed lunch behind."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTrip7"
			content ="Nathan runs back home to get his packed lunch and runs all the way back to the park."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTrip8"
			content ="It is ten minutes walk across park or 15 minutes to walk round it. His mother doesn’t like him going through the park. He takes a minute to decide what to do."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTrip9"
			content ="On the other side of the park has to wait 3 minutes for the traffic lights to change so he can cross the road safely."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTrip10"
			content ="It takes 15 minutes to walk from the park to school."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTrip11"
			content ="Running is twice as fast as walking."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTrip12"
			content ="The bus leaves the school at 9.20 am"
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
				<tns:item content-type="text/plain"
			id="SchoolTrip13"
			content ="If Nathan walks to school it usually takes him three times as long as in the car. His journey takes him past the park."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTrip14"
			content ="The shops next to the park are busy with people buying newspapers and children getting sweets."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="SchoolTripTitle"
			content ="Does Nathan miss the bus for the school trip?"
			contentItemType ="MultiLineTextLabel"
			category = "title"
			>
			<tns:attributes></tns:attributes>
		</tns:item>

	</tns:items>
</tns:contentitems>

=== synergynet/synergynet2.1/SynergySpace2.1/src_synergynet/data/mysteries/dinnerdisaster/dinnerdisaster.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:contentitems
	xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tel.dur.ac.uk/xml/schemas/mystery_schema ../../data/contentitems/schemas/contentitems_schema.xsd "
	author="Steve Higgins"
	description="Dinner disaster: can you work out what Mike should have to eat? "
	license="restricted" name="Dinner disaster"
	
	locationFile="data/mysteries/dinnerdisaster/dinnerdisaster_location.xml"
	appearanceFile="data/mysteries/dinnerdisaster/dinnerdisaster_apparence.xml"
	gestureFile="data/mysteries/dinnerdisaster/dinnerdisaster_gesture.xml"
	defaultAppearanceFile="data/mysteries/defaultApparence.xml"
	
	>
	<tns:items>
		<tns:item content-type="text/plain"
			id="DD1"
			content = "The new cook at school, Mrs Muxedip, has mixed up the trays with the childrenâ€™s school dinners on."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="DD2"
			content ="&quot;YUCK!&quot; cried Matilda, making a face at the slice of pizza in front of her. &quot;I can't stand pepperoni!&quot;" 
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="DD3"
			content ="&quot;Don't look at me,&quot; pouted Raoul. &quot;I hate any food with cheese on it.&quot; At that, he pushed away his cheeseburger."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="DD4"
			content = "&quot;Hey, anybody want these chicken wings?&quot; asked Khaley. &quot;I don't like anything with meat in it.&quot;"
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="DD5"
			content ="Mike scooped up a spoonful of his yogurt and grumbled, &quot;Everybody knows I'm allergic to this stuff.&quot;" 
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="DD6"
			content ="&quot;Well, yogurt is the only thing I like on the menu,&quot; replied Tanya. &quot;And there's no way I'm going to eat THIS!&quot; At that, she poked her salad with a fork."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="DDTitle"
			content ="Can you work out what Mike should have to eat?"
			contentItemType ="MultiLineTextLabel"
			category ="title"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
	</tns:items>
</tns:contentitems>
