=== synergynet/synergynet2.1/SynergySpace2.1/bin/data/contentitems/schemas/contentitems_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://tel.dur.ac.uk/xml/schemas/contentitems_schema" xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_schema" elementFormDefault="qualified">

    <complexType name="ContentItemsType">
    	<sequence>
    		<element name="items" type="tns:ItemListType" minOccurs="1"
    			maxOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="description" type="string" use="required"></attribute>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="author" type="string" use="required"></attribute>
    	<attribute name="license" type="string" use="required"></attribute>
    	<attribute name="question" type="string"></attribute>
    	
    	<attribute name="locationFile" type="string"></attribute>
    	<attribute name="appearanceFile" type="string"></attribute>
    	<attribute name="defaultAppearanceFile" type="string"></attribute>
    	<attribute name="gestureFile" type="string"></attribute>

    </complexType>

    <element name="contentitems" type="tns:ContentItemsType"></element>

    <complexType name="ItemType">
    	<sequence>
    		<element name="attributes" type="string"></element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="content-type" type="string"></attribute>  	
    	<attribute name="contentItemType" type="string" use="required"></attribute>  
    	<attribute name="category" type="string" use="required"></attribute> 	
    	<attribute name="imagePath" type="string"></attribute> 
    	<attribute name="content" type="string"></attribute> 
    	
    </complexType>


    <complexType name="ItemListType">
    	<sequence>
    		<element name="item" type="tns:ItemType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <attribute name="NewAttribute" type="string"></attribute>

</schema>

=== synergynet/synergynet2.1/SynergySpace2.1/bin/data/mysteries/great_fire_of_london/great_fire_of_london.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:contentitems
	xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tel.dur.ac.uk/xml/schemas/mystery_schema ../../data/contentitems/schemas/contentitems_schema.xsd "
	author="Steve Higgins"
	description="History mystery based on the Great Fire of London"
	license="restricted" name="The Great Fire of London"
	
	locationFile="data/mysteries/great_fire_of_london/great_fire_of_london_location.xml"
	appearanceFile="data/mysteries/great_fire_of_london/great_fire_of_london_apparence.xml"
	gestureFile="data/mysteries/great_fire_of_london/great_fire_of_london_gesture.xml"
	defaultAppearanceFile="data/mysteries/defaultApparence.xml"
	>
	<tns:items>
		<tns:item content-type="text/plain"
			id="FOL1"
			content = "Thomas Farrinor was Baker to King Charles II"
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL2"
			content ="The Baker said that he thought he had put out his oven, but embers from the fire set light to nearby firewood." 
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL3"
			content ="The Baker's maid was the first victim of the Great Fire."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL4"
			content = "Most of the houses and buildings were made of wood and many had thatched roofs."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL5"
			content ="The people tried to put the fire out with buckets of water." 
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL6"
			content ="Hundreds of rats lived in Pudding Lane."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL7"
			content ="Lots of people spent time saving their things instead of trying to stop the fire spreading."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL8"
			content ="On Wednesday night the wind hushed and the fire burned gently."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL9"
			content ="The buildings caught fire very easily."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL10"
			content ="The fire destroyed about four-fifths of the city, or more than 430 acres."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL11"
			content ="The Baker forgot to turn off his oven."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL12"
			content ="Riverfront warehouses were bursting full of oil, tallow and other combustible goods."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL13"
			content ="The Baker lived in Pudding Lane."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL14"
			content ="Sparks from the Baker's burning house fell on hay and straw at the Star Inn."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL15"
			content ="The fire started in Pudding Lane."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL16"
			content ="The buckets were made of wood and leather."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL17"
			content ="Houses were pulled down to stop the fire spreading, but wood and rubbish were left lying in the street."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL18"
			content ="The fire began at night when everybody was asleep."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL19"
			content ="The strong easterly wind kept the fire burning."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOL20"
			content ="About 13,200 houses, nearly 90 parish churches, and nearly 50 livery company halls were burnt down."
			contentItemType ="MultiLineTextLabel"
			category ="content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="FOLTitle"
			content ="Why did 16 people die in the Great Fire of London?"
			contentItemType ="MultiLineTextLabel"
			category ="title"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
	</tns:items>
</tns:contentitems>

=== synergynet/synergynet2.1/SynergySpace2.1/src_synergynet/data/mysteries/tipping_waitresses/tipping_waitresses.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:contentitems
	xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tel.dur.ac.uk/xml/schemas/contentitems_schema ../../data/contentitems/schemas/contentitems_schema.xsd "
	author="Steve Higgins"
	description="Mystery based on the film Reservior Dogs" 
	license="restricted"
	name="Tipping Waitresses"

	locationFile="data/mysteries/tipping_waitresses/tipping_waitresses_location.xml"
	appearanceFile="data/mysteries/tipping_waitresses/tipping_waitresses_apparence.xml"
	gestureFile="data/mysteries/tipping_waitresses/tipping_waitresses_gesture.xml"
	defaultAppearanceFile="data/mysteries/defaultApparence.xml"

	>
	<tns:items>
		<tns:item content-type="text/plain"
			id="TW1"
			content = "Nice Guy Eddie thinks that Mr Pink should tip the waitress."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW2"
			content ="Mr Pink says that he does not believe in tipping waitresses." 
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW3"
			content ="Mr Pink says that if the waitress is not making enough money, she could always quit her job."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW4"
			content = "Mr Pink states that he will tip when someone deserves a tip, but not just because society says he should."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW5"
			content ="Mr Pink says the waitress did not do anything special." 
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW6"
			content ="Mr. Pink claims she only refilled his coffee cup three times."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW7"
			content ="Mr Pink says that she couldn’t have been 'too busy' to fill it more, the words 'too busy' should not be in a waitress’ vocabulary."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW8"
			content ="Mr Pink claims that waitresses are paid the minimum wage."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW9"
			content ="Mr Pink says we don’t expect to tip at McDonalds, even though the staff there serve you food."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW10"
			content ="Mr Pink says that they may well be taxed on the basis that they are given tips, which is wrong, but that this is nothing to do with him or the argument."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW11"
			content ="Mr Pink says that they could do a better job if they trained, such as by learning to type."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW12"
			content ="Mr Blue claims that the wages for waitresses are low."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW13"
			content ="Mr Blue argues that the girl was nice."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW14"
			content ="Mr Blonde suggests that she really was too busy to refill his cup six times."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW15"
			content ="Mr Blue suggests that she’s counting on tips to live."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW16"
			content ="Mr White counters that she’ll be taxed on the tips she is expected to get, even if she doesn’t get them."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW17"
			content ="Mr White says she works really hard."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW18"
			content ="Mr White says that they work harder here than at McDonalds."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW19"
			content ="Mr White says waitressing is the one job an unskilled woman can live on because of the tips."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TW20"
			content ="Joe Cabot paid for everyone’s breakfast at the diner."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="TWTitle"
			content ="Was Mr Pink right not to want to tip the waitress?"
			contentItemType ="MultiLineTextLabel"
			category = "title"
			>
			<tns:attributes></tns:attributes>
		</tns:item>

	</tns:items>
</tns:contentitems>

=== synergynet/synergynet2.1/SynergySpace2.1/src_synergynet/data/diamondranking/ict/ict.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:contentitems
	xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tel.dur.ac.uk/xml/schemas/contentitems_schema ../../data/contentitems/schemas/contentitems_schema.xsd "
	author="Steve Higgins"
	description="ICT for Learning"
	license="restricted" name="ICT for Learning"
	
	locationFile="data/diamondranking/ict/ict_location.xml"
	appearanceFile="data/diamondranking/ict/ict_apparence.xml"
	gestureFile="data/diamondranking/ict/ict_gesture.xml"
	defaultAppearanceFile="data/diamondranking/defaultApparence.xml"

	>
	<tns:items>
		<tns:item content-type="text/plain"
			id="ICT1"
			content = "ICT improves learnersâ€™ motivation to learn and their engagement in the learning process."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT2"
			content ="Technology closes the gender gap between boys and girls in school." 
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT3"
			content ="Investment in technology  in education is a cost-effective way to improve teaching and learning."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT4"
			content = "Using technology in schools/universities raises attainment in learning."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT5"
			content ="ICT enables the development of more effective teaching." 
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT6"
			content ="The additional skills learners develop through using technology will benefit them more widely."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT7"
			content ="Education should use technology to keep up with technological advances in society."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT8"
			content ="Technology makes teaching and assessment easier and more efficient."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT9"
			content ="Technology makes education more accessible for all learners."
			contentItemType ="MultiLineTextLabel"
			category = "content"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT10"
			contentItemType ="Frame"
			category = "frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT11"
			contentItemType ="Frame"
			category = "frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT12"
			contentItemType ="Frame"
			category = "frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT13"
			contentItemType ="Frame"
			category = "frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT14"
			contentItemType ="Frame"
			category = "frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT15"
			contentItemType ="Frame"
			category = "frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT16"
			contentItemType ="Frame"
			category = "frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT17"
			contentItemType ="Frame"
			category = "frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT18"
			contentItemType ="Frame"
			category = "frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="ICT19"
			content ="ICT for Learning"
			contentItemType ="MultiLineTextLabel"
			category = "title"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
	</tns:items>
</tns:contentitems>

=== synergynet/synergynet2.1/SynergySpace2.1/bin/data/diamondranking/imagetest/imagetest.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:contentitems
	xmlns:tns="http://tel.dur.ac.uk/xml/schemas/contentitems_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tel.dur.ac.uk/xml/schemas/contentitems_schema ../../data/contentitems/schemas/contentitems_schema.xsd "
	author="Steve Higgins"
	description="ICT for Learning"
	license="restricted" name="ICT for Learning"

	locationFile="data/diamondranking/imagetest/imagetest_location.xml"
	appearanceFile="data/diamondranking/imagetest/imagetest_apparence.xml"
	gestureFile="data/diamondranking/imagetest/imagetest_gesture.xml"
	defaultAppearanceFile="data/diamondranking/defaultApparence.xml"
	
	>
	<tns:items>
		<tns:item content-type="text/plain"
			id="IT1"
			content = "Speak Up"
			imagePath = "data/diamondranking/imagetest/image/speakup.png"
			contentItemType ="ImageTextLabel"
			category ="imageText"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT2"
			content ="Read the Information" 
			imagePath = "data/diamondranking/imagetest/image/readtheinformation.png"
			contentItemType ="ImageTextLabel"
			category ="imageText"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT3"
			content ="Listen to Each Other"
			imagePath = "data/diamondranking/imagetest/image/listentoeachother.png"
			contentItemType ="ImageTextLabel"
			category ="imageText"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT4"
			content = "Say What We Think"
			imagePath = "data/diamondranking/imagetest/image/saywhatwethink.png"
			contentItemType ="ImageTextLabel"
			category ="imageText"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT5"
			content ="Work Together" 
			imagePath = "data/diamondranking/imagetest/image/worktogether.png"
			contentItemType ="ImageTextLabel"
			category ="imageText"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT6"
			content ="Share Ideas"
			imagePath = "data/diamondranking/imagetest/image/shareideas.png"
			contentItemType ="ImageTextLabel"
			category ="imageText"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT7"
			content ="Talk Together"
			imagePath = "data/diamondranking/imagetest/image/talktogether.jpg"
			contentItemType ="ImageTextLabel"
			category ="imageText"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT8"
			content ="Work Faster"
			imagePath = "data/diamondranking/imagetest/image/workfaster.png"
			contentItemType ="ImageTextLabel"
			category ="imageText"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT9"
			content ="Understand Things"
			imagePath = "data/diamondranking/imagetest/image/understandthework.png"
			contentItemType ="ImageTextLabel"
			category ="imageText"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT10"
			contentItemType ="Frame"
			category ="frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT11"
			contentItemType ="Frame"
			category ="frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT12"
			contentItemType ="Frame"
			category ="frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT13"
			contentItemType ="Frame"
			category ="frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT14"
			contentItemType ="Frame"
			category ="frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT15"
			contentItemType ="Frame"
			category ="frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT16"
			contentItemType ="Frame"
			category ="frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT17"
			contentItemType ="Frame"
			category ="frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT18"
			contentItemType ="Frame"
			category ="frame"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
		<tns:item content-type="text/plain"
			id="IT19"
			content ="Multi-touch is good at helping us..."
			contentItemType ="MultiLineTextLabel"
			category = "title"
			>
			<tns:attributes></tns:attributes>
		</tns:item>
	</tns:items>
</tns:contentitems>
