=== synergynet/synergynet2.1/SynergySpace2.1/src_synergynet/config/schemas/tableconfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://tel.dur.ac.uk/xml/schemas/tableconfiguration"
	xmlns:tns="http://tel.dur.ac.uk/xml/schemas/tableconfiguration"
	elementFormDefault="qualified">


	<complexType name="StartupOptionsType">
		<sequence>
			<element name="splashScreenResource" type="string"
				minOccurs="1" maxOccurs="1">
			</element>
			<element name="splashScreenEnabled" type="boolean"
				minOccurs="1" maxOccurs="1">
			</element>
			<element name="forceApplication" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="mode" maxOccurs="1" minOccurs="0">
				<simpleType>
					<restriction base="string">
						<enumeration value="client"></enumeration>
						<enumeration value="controller"></enumeration>
						<enumeration value="projector"></enumeration>
					</restriction>
				</simpleType>
			</element>
		</sequence>
		
	</complexType>
	<complexType name="ServiceType">
		<sequence>
			<element name="depends" type="tns:ServiceListType" maxOccurs="1"
				minOccurs="0"></element>
		</sequence>
		<attribute name="classname" type="string" use="required"></attribute>
		<attribute name="enabled" type="boolean" use="optional"
			default="true">
		</attribute>
	</complexType>
	<complexType name="ServiceListType">
		<sequence maxOccurs="unbounded" minOccurs="1">
			<element name="service" type="tns:ServiceType"></element>
		</sequence>
	</complexType>

    <complexType name="ConfigurationType">
    <sequence>
            <element name="options" type="tns:StartupOptionsType" maxOccurs="1" minOccurs="1"></element>
            <element name="applications" type="tns:ApplicationListType"
    		maxOccurs="1" minOccurs="1">
    	</element>
    	<element name="services" type="tns:ServiceListType"
    		maxOccurs="1" minOccurs="0">
    	</element>
    </sequence>
    </complexType>

    <element name="config" type="tns:ConfigurationType">
    </element>

    <complexType name="ApplicationListType">
    	<sequence>
    		<element name="application" type="tns:ApplicationType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ApplicationType">
    	<attribute name="configpath" type="string"></attribute>
        <attribute name="enabled" type="boolean" use="optional" default="true">
    	</attribute>
        <attribute name="default" type="boolean" use="optional" default="false"></attribute>
    </complexType>
</schema>

=== synergynet/synergynet2.1/SynergySpace2.1/bin/config/demotableconfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:config xmlns:tns="http://tel.dur.ac.uk/xml/schemas/tableconfiguration"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tel.dur.ac.uk/xml/schemas/tableconfiguration ./schemas/tableconfiguration.xsd ">

	<tns:options>
		<tns:splashScreenResource>media/images/splashscreens/synergynet.png</tns:splashScreenResource>
		<tns:splashScreenEnabled>false</tns:splashScreenEnabled>
		<tns:mode>client</tns:mode>
	</tns:options>

	<!-- Please keep the list alphabetical and use enabled attribute to disable/enable -->
	<tns:applications>
	
		<tns:application configpath="synergynet/table/apps/mainmenu/synergynetapplication.xml" default="true" />
		<tns:application configpath="synergynet/table/apps/borderstudy/synergynetapplication.xml" enabled="false"/>
		<tns:application configpath="synergynet/table/apps/conceptmap/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/contentitemgallery/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/controlclient/synergynetapplication.xml" enabled="false"/>
		<tns:application configpath="synergynet/table/apps/diamondranking/synergynetapplication.xml"  enabled="true"/>
		<tns:application configpath="synergynet/table/apps/dissection/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/docviewer/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/dominos/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/geognetworkflick/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/lightbox/synergynetapplication.xml" enabled="true"/>		
		<tns:application configpath="synergynet/table/apps/livingmaps/synergynetapplication.xml" enabled="false"/>
		<tns:application configpath="synergynet/table/apps/mapapp/synergynetapplication.xml"  enabled="true"/>
		<tns:application configpath="synergynet/table/apps/mathpadapp/synergynetapplication.xml" enabled="false"/>
		<tns:application configpath="synergynet/table/apps/mathpadtableportal/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/meteorstrike/synergynetapplication.xml"  enabled="true"/>
		<tns:application configpath="synergynet/table/apps/mt3dmaps/synergynetapplication.xml" enabled="false"/>
		<tns:application configpath="synergynet/table/apps/mysteries/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/mysteriestableportal/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/networkflick/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/networkpresenter/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/pong/synergynetapplication.xml" enabled="false"/>
		<tns:application configpath="synergynet/table/apps/rapidnetworking/synergynetapplication.xml"  enabled="false"/>
		<tns:application configpath="synergynet/table/apps/realgravity/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/remotecontrol/synergynetapplication.xml" enabled="false"/>
		<tns:application configpath="synergynet/table/apps/replay/synergynetapplication.xml" enabled="false"/>
		<tns:application configpath="synergynet/table/apps/researchpuzzle/synergynetapplication.xml" enabled="false"/>
		<tns:application configpath="synergynet/table/apps/sandbox/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/splasher/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/tablepositionsetup/synergynetapplication.xml" enabled="false"/>
		<tns:application configpath="synergynet/table/apps/teapots/synergynetapplication.xml" enabled="false"/>
		<tns:application configpath="synergynet/table/apps/threeDButtonsExperiment/synergynetapplication.xml" enabled="false"/>	
		<tns:application configpath="synergynet/table/apps/threeDInteraction/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/threeDPuzzle/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/threedmanipulation/synergynetapplication.xml" enabled="true"/>	
		<tns:application configpath="synergynet/table/apps/twentyfourpoint/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/watertank/synergynetapplication.xml" enabled="true"/>		
		<tns:application configpath="synergynet/table/apps/xmlpuzzle/synergynetapplication.xml" enabled="true"/>
		
	</tns:applications>
</tns:config>

=== synergynet/synergynet2.1/SynergySpace2.1/src_synergynet/config/teachertableconfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:config xmlns:tns="http://tel.dur.ac.uk/xml/schemas/tableconfiguration"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tel.dur.ac.uk/xml/schemas/tableconfiguration ./schemas/tableconfiguration.xsd ">
	
	<tns:options>
		<tns:splashScreenResource>media/images/splashscreens/synergynet.png</tns:splashScreenResource>
		<tns:splashScreenEnabled>false</tns:splashScreenEnabled>
		<tns:mode>controller</tns:mode>
	</tns:options>
	
	<tns:applications>
		<tns:application configpath="synergynet/table/apps/mainmenu/synergynetapplication.xml" default="true" />
		<tns:application configpath="synergynet/table/apps/splasher/synergynetapplication.xml" />
		<tns:application configpath="synergynet/table/consoleapps/control/synergynetapplication.xml" />
		<tns:application configpath="synergynet/table/consoleapps/presence/synergynetapplication.xml" />
		<tns:application configpath="synergynet/table/apps/mysteries/synergynetapplication.xml" />
		<tns:application configpath="synergynet/table/apps/mathpadapp/synergynetapplication.xml" />
		<tns:application configpath="synergynet/table/apps/mysteriestableportal/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/geognetworkflick/synergynetapplication.xml" enabled="true"/>
		<tns:application configpath="synergynet/table/apps/mathpadtableportal/synergynetapplication.xml" enabled="true"/>
		
	</tns:applications>
	
	<tns:services>
		<tns:service
			classname="synergynet.services.net.tablecomms.client.TableCommsClientService"
			enabled="true">
			<tns:depends>
				<tns:service
					classname="synergynet.services.net.netservicediscovery.NetworkServiceDiscoveryService" />
			</tns:depends>
		</tns:service>
	</tns:services>
</tns:config>
